import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import {
    getDeviceLabel,
    getUserDisplayName,
    isAutoGeneratedDisplayName,
    resetDeviceLabelCacheForTests,
    setUserDisplayName,
} from '@/lib/device-label';

function createStorage() {
    const map = new Map<string, string>();
    return {
        getItem: (key: string) => map.get(key) ?? null,
        setItem: (key: string, value: string) => {
            map.set(key, value);
        },
        removeItem: (key: string) => {
            map.delete(key);
        },
        clear: () => map.clear(),
    };
}

describe('device-label', () => {
    const storage = createStorage();

    beforeEach(() => {
        storage.clear();
        vi.stubGlobal('localStorage', storage);
        vi.stubGlobal('navigator', {
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X)',
            platform: 'iPhone',
            maxTouchPoints: 5,
        });
        resetDeviceLabelCacheForTests();
    });

    afterEach(() => {
        resetDeviceLabelCacheForTests();
        vi.unstubAllGlobals();
    });

    it('prefers user override over auto label', () => {
        setUserDisplayName('Zang');
        expect(getUserDisplayName()).toBe('Zang');
        expect(getDeviceLabel()).toBe('Zang');
    });

    it('falls back to iPhone from UA when no override', () => {
        expect(getDeviceLabel()).toBe('iPhone');
    });

    it('returns TV for tv clients', () => {
        expect(getDeviceLabel({ isTvClient: true })).toBe('TV');
    });

    it('detects auto-generated placeholders', () => {
        expect(isAutoGeneratedDisplayName('Remote #2')).toBe(true);
        expect(isAutoGeneratedDisplayName('iPhone')).toBe(true);
        expect(isAutoGeneratedDisplayName('Zang')).toBe(false);
        expect(isAutoGeneratedDisplayName('Pixel 7')).toBe(false);
    });
});
